use_frameworks!

target 'QUIckControlExample' do
  	pod 'QUIckControl', :git => 'https://github.com/k-o-d-e-n/QUIckControl.git', :branch => 'pod_install'
  	pod 'PinCodeControl', :git => 'https://github.com/k-o-d-e-n/QUIckControl.git', :branch => 'pod_install'
  	pod 'Statable'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
