use_frameworks!

target 'QUIckControlExample' do
  	pod 'PinCodeControl' # loaded all depended pods (QUIckControl, Statable)
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
