use_frameworks!

target 'QUIckControlExample' do
#    pod 'PinCodeControl' # loaded all depended pods (QUIckControl, Statable)
    pod 'PinCodeControl', :path => '../'
    pod 'QUIckControl', :path => '../'
#    pod
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.1'
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
